basket/urls.py
from django.conf.urls import url
from views import AddToBasket,ShowBasket

urlpatterns = [
    url(r'^car-detail/(?P<car_id>\d+)/addbasket/', AddToBasket.as_view(),
        name='addbasket'),
    url(r'^basket/(?P<action>.+)', ShowBasket.as_view(), name='showbasket'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from users import views as userviews
from cars import views as carviews


urlpatterns = [
    url(r'^user/', include('users.urls')),
    url(r'^$',  carviews.IndexView.as_view(), name='cars'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', userviews.login),
    url(r'^registration/', userviews.registration),
    url(r'^car/', include('cars.urls',namespace="cars")),
    url(r'^basket/', include('basket.urls',namespace="basket")),
]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from users import views as userviews
from cars.views import index

urlpatterns = [
    url(r'^user/', include('users.urls')),
    url(r'^$', index),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', userviews.login),
    url(r'^registration/', userviews.registration),
    url(r'^cars/', include('cars.urls', namespace='cars')),
]

basket/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse
from cars.models import Car
from django.shortcuts import get_object_or_404
from utils import get_mongo_database


class ShowBasket(TemplateView):
    template_name = 'basket.html'

    def get_context_data(self, **kwargs):
        context = super(ShowBasket, self).get_context_data(**kwargs)
        action = kwargs.get('action')
        if self.request.session.get('basket'):
            basket = self.request.session.get('basket')
            car_list = []
            total = 0
            for i in basket:
                car_id = basket[int(i)-1]
                car = get_object_or_404(Car, pk=car_id)
                car_list.append(car)
                total += int(car.price)
            context.update({'carlist': car_list, 'total': total})
        else:
            self.request.session.update({'basket': []})
        if action == "clear":
            self.request.session.update({'basket': []})
            context.update({'carlist': [], 'total': 0})
        if action == "buy":
            car_id = kwargs.get('car_id')
            car = get_object_or_404(Car, pk=car_id)
            car.delete()
            db = get_mongo_database()
            mongocars = db.cars
            mongocars.remove({"sql_id": car_id})
            self.request.session.update({'basket': []})
            context.update({'carlist': [], 'total': 0})
        return context


class AddToBasket(TemplateView):
    template_name = 'basket.html'

    def get(self, request, *args, **kwargs):
        car_id = kwargs.get('car_id')
        context = super(AddToBasket, self).get_context_data(**kwargs)
        if request.session.get('basket'):
            if not car_id in request.session['basket']:
                request.session['basket'].append(car_id)
            else:
                context.update({'status': 'already added'})
        else:
            request.session.update({'basket': []})
            request.session['basket'].append(car_id)
        url_to_redirect = reverse('cars:car_detail', kwargs={'car_id': car_id})
        return redirect(url_to_redirect)

templates/Item_page.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load i18n %}


{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/item.css' %}" />
<h1 style="color: white">{{ descriptions.name }} </h1>
<div id="mainblock">

    <div class="itemdiv">
    <ul>{% for name, value in descriptions.get_fields %}<li>{{ name }}: {{ value }} </li>{% endfor %}</ul>
       <a href="{% url 'basket:addbasket' car_id=descriptions.id %}">
           <button class="addto">{% trans 'Add to basket' %}</button>
       </a>
       <h3>{{ status }} </h3>
    </div>
    <div class="comment">
        {% if request.user.is_authenticated %}
            <form action='.'  method="post">
                {% csrf_token %}
                <table>{{ form.as_table }}</table>
                <button type='submit'>{% trans 'Send' %}</button>
            </form>
             {% for comment in Comments %}<hr>{{ comment }}{% endfor %}
        {% else %}
            <h1>{% trans 'Sorry but only authenticated users can post the messeges' %}</h1>
        {% endif %}
    </div>

</div>

{% endblock %}

templates/base.html
{% load staticfiles %}

{% load i18n %}


<html lang="en">

<head>

<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />


<title>Car Shop {% block title %}{% endblock %}</title>

</head>

<body>
    <!--==============================header=================================-->
    <header>
          <div class="main">
              <h1><a href="/"><img src="/static/img/logo.png"></a></h1>
          </div>
        <div>

          <div id="framediv">
           <div id="formdiv">
              <div><a href="/login">{% trans "login" %}</a> <a href="/registration">{% trans "registeration" %}</a></div>
              <form action="/i18n/setlang/" method="POST">
                      {% get_available_languages as LANGUAGES %}
                      {% csrf_token %}
                      <select name="language">
                        {% for lang in LANGUAGES %}
                          <option value="{{ lang.0 }}">{{ lang.1 }}</option>
                        {% endfor %}
                      </select>
                      <input id = "localbutton" type="submit" value="{% trans 'change' %}" />
               </form>
            </div>
          </div>

           {% if request.user.is_authenticated %}
                <div id="framediv"><a href="{% url 'basket:showbasket' action='show' %}"><img src="../static/img/basket.jpg"></a></div>
           {% endif %}

          <div id="framediv"><a href="{% url 'search' %}"><img src="/static/img/search.jpg"></a></div>

        </div>

    </header>

    {% block content %}
    {% endblock %}

    <!--==============================footer=================================-->
    <footer>
        <div class="main">
            <span>Copyright &copy; <a href="#">Domain Name</a> All Rights Reserved</span>
        </div>
    </footer>
</body>

</html>

templates/basket.html
{% extends 'base.html' %}

{% load i18n %}

{% load staticfiles %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />

<h1>{% trans 'Its basket page' %}</h1>

<div id="mainblock">
    <form action='.'  method="post">
        {% csrf_token %}
         {% for item in carlist %}<hr>{{ item.name }} : Price {{ item.price }} {% endfor %}
        <h2>Total {{ total }}</h2>
        <a href="{% url 'basket:showbasket' action='buy' %}" > {% trans 'Buy' %} </a>
        <a href="{% url 'basket:showbasket' action='clear' %}">{% trans 'Clear' %} </a>
    </form>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<h1 style="color: white">
   {% trans "Hello,"%} {% if request.user.is_authenticated %}{{ request.user }}{% else %}guest,{% endif %} {% trans "you are at index page"%}
</h1>
<div id="mainblock">

    <div id="itemlist">
        {% for car in cars %}
            <a href="{{ car.get_absolute_url }}">
                <div id="cars">
                    {{ car }}
                </div>
            </a>
        {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if cars.has_previous %}
                <a href="?page={{ cars.previous_page_number }}">{% trans "previous" %}</a>
            {% endif %}

            <span class="current">
                {% trans "Page" %} {{ cars.number }} {% trans "of" %} {{ cars.paginator.num_pages }}.
            </span>

            {% if cars.has_next %}
                <a href="?page={{ cars.next_page_number }}">{% trans "next" %}</a>
            {% endif %}
        </span>
    </div>
</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}


<div id="container">
<form action='.'  method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <div id="lower">
        <button type='submit' value="Войти">{% trans 'Submit' %}</button>
        <a href="/registration"><button type="button">{% trans 'Registration' %}</button></a>
    </div>
</form>
{% endblock content %}
</div>

templates/massage.html
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to site</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
</head>
<body>
    <h1>Welcome to our site!</h1>
    <p>{{ username }} you became a part of beautiful community of django developers</p>
    <p>This project helps us to become greater django guru.So wake up neo.Your activation code is
        http://127.0.0.1:8000/user/activate/{{ security_key }}</p>
</body>
</html>

templates/registration.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<div id="regform">
<form action='.'  method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <div id="lower">
        <button type='submit' value="">{% trans 'Submit' %}"</button>
    </div>
</form>
{% endblock content %}
</div>

templates/search.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

<h1 style="color: white">{% trans 'Searching page' %}</h1>
<div id="mainblock">
    <div>
        <form action="{% url 'search' %}"  method="get">
            {% csrf_token %}
            <table align="center">
                {% for field in form %}
                  {% if forloop.first %}
                    <tr><td>{{ field.label }}{{ field }}</td></tr>
                  {% endif %}
                  {% if forloop.counter > 1 %}
                    {% if forloop.counter|divisibleby:"2" %}
                        <tr><td align="right">{{ field.label }}{{ field }}</td>
                    {% else %}
                        <td>{{ field.label }}{{ field }}</td></tr>
                    {% endif %}
                  {% endif %}
                {% endfor %}
            </table>
            <div id="lower">
                <button type='submit' value="">{% trans 'Search' %}</button>
            </div>
        </form>
        <ul>
            {% for car in search_res %}
                <div><li><a class="colored_grey" href="{{ car.get_absolute_url }}">
                        {{ car }}
                </a></li></div>
            {% endfor %}
        </ul>
    </div>


    <div class="pagination">
            <span class="step-links">
                {% if search_res.has_previous %}
                    <a href="?page={{ search_res.previous_page_number }}">{% trans 'previous' %}</a>
                {% endif %}

                <span class="current">
                    {{ search_res.number }} {% trans 'of' %} {{ search_res.paginator.num_pages }}.
                </span>

                {% if search_res.has_next %}
                    <a href="?page={{ search_res.next_page_number }}">{% trans 'next' %}</a>
                {% endif %}
            </span>
    </div>
</div>

{% endblock %}